#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
cd $OPENSHIFT_REPO_DIR/wsgi
rm -f static/index.html
$OPENSHIFT_RUN_DIR/../virtenv/bin/python generate.py
mv index.html static/index.html
