callback([
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1617217115.8685133
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "major",
        "new_global_status": "major",
        "message": "Git seems unhappy, being investigated",
        "changedate": 1617196161.1282456
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1617102444.4415824
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "major",
        "new_global_status": "major",
        "message": "Uploading to the lookaside is current not working and being investigated",
        "changedate": 1617097806.7054377
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "fas",
            "koschei"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1616948923.814176
    },
    {
        "changetype": "single",
        "service": "fas",
        "status": "major",
        "new_global_status": "major",
        "message": "Openshift outage currently ongoing, no ETA",
        "changedate": 1616946010.7654316
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "koschei"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Openshift outage currently ongoing, no ETA",
        "changedate": 1616945779.069585
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1616710876.7276564
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "We are transitioning to new AAA",
        "changedate": 1616581125.0682263
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1616187934.6552162
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "OpenShift Problems impacting all services",
        "changedate": 1616186243.2082598
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers outage, https://pagure.io/fedora-infrastructure/issue/9734",
        "changedate": 1615983523.6719916
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1610546552.757733
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "koji is growing a little covid-belly and running out of space, we're looking for some more",
        "changedate": 1610540887.102674
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1610528843.8470192
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "major",
        "new_global_status": "major",
        "message": "Something is up and being investigated",
        "changedate": 1610528510.41115
    },
    {
        "changetype": "multiple",
        "services": [
            "koji",
            "registry"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1607711197.182578
    },
    {
        "changetype": "single",
        "service": "registry",
        "status": "major",
        "new_global_status": "major",
        "message": "server outage",
        "changedate": 1607710690.4134338
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "server outage",
        "changedate": 1607710521.1056192
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1607602141.2806523
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "Server down, investigation in progress",
        "changedate": 1607436190.8344805
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "Server is dead. No way to remote fix. Downtime unknown.",
        "changedate": 1607434993.3202527
    },
    {
        "changetype": "single",
        "service": "zodbot",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1606934244.6762269
    },
    {
        "changetype": "single",
        "service": "zodbot",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "test",
        "changedate": 1606934181.3525338
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1606827107.6376927
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers outage, https://pagure.io/fedora-infrastructure/issue/9502",
        "changedate": 1606826964.9385772
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1605263067.8806794
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers outage, https://pagure.io/fedora-infrastructure/issue/9459",
        "changedate": 1605255010.7407851
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1605137471.7066238
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "planned outage",
        "changedate": 1605128472.6829512
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1604608753.956175
    },
    {
        "changetype": "single",
        "service": "krb",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1604608740.0606806
    },
    {
        "changetype": "single",
        "service": "krb",
        "status": "major",
        "new_global_status": "major",
        "message": "auth is down, looking at it",
        "changedate": 1604605385.4606543
    },
    {
        "changetype": "multiple",
        "services": [
            "koji",
            "pkgs"
        ],
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1601992480.9984765
    },
    {
        "changetype": "multiple",
        "services": [
            "koji",
            "pkgs"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "PDC outage ongoing and under investigation",
        "changedate": 1601989935.9691107
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1601559472.4518712
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "major",
        "new_global_status": "major",
        "message": "Announced outage ongoing",
        "changedate": 1601539460.9335222
    },
    {
        "changetype": "single",
        "service": "koschei",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1599141816.983085
    },
    {
        "changetype": "single",
        "service": "koschei",
        "status": "major",
        "new_global_status": "major",
        "message": "Koschei frontend is down",
        "changedate": 1599137042.487468
    },
    {
        "changetype": "single",
        "service": "people",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1599055779.570344
    },
    {
        "changetype": "single",
        "service": "people",
        "status": "major",
        "new_global_status": "major",
        "message": "SSL certs issues, we're looking into it",
        "changedate": 1599055459.5208125
    },
    {
        "changetype": "single",
        "service": "packages",
        "status": "major",
        "new_global_status": "major",
        "message": "Read the infra status link at the top",
        "changedate": 1598952949.0440068
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1597926031.6875284
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "Koji is out of disk space.",
        "changedate": 1597924177.7796896
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "read the infra status link at the top",
        "changedate": 1597279927.5636926
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1597279914.478267
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "planned outage",
        "changedate": 1597266731.782837
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "major",
        "message": "Copr servers outage, https://pagure.io/fedora-infrastructure/issue/9218",
        "changedate": 1597215558.2422955
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1597154222.5688148
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "read the infra status link at the top",
        "changedate": 1597154109.8068125
    },
    {
        "changetype": "multiple",
        "services": [
            "retrace",
            "koji"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "abrt: read the infra status link at the top - koji: signing is down",
        "changedate": 1597136205.02514
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "read the infra status link at the top",
        "changedate": 1596993789.628756
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1596941594.132308
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "issues with openshift cluster",
        "changedate": 1596940148.6626291
    },
    {
        "changetype": "single",
        "service": "fas",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1596837499.120745
    },
    {
        "changetype": "single",
        "service": "fas",
        "status": "major",
        "new_global_status": "major",
        "message": "id and fas issues being investigated",
        "changedate": 1596835594.9887054
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1596746190.7342474
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "services down due to openshift failures",
        "changedate": 1596715336.414444
    },
    {
        "changetype": "multiple",
        "services": [
            "koji",
            "packages",
            "retrace"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1596682812.0709844
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "scheduled",
        "new_global_status": "minor",
        "message": "planned outage",
        "changedate": 1596665399.0845547
    },
    {
        "changetype": "single",
        "service": "packages",
        "status": "minor",
        "new_global_status": "minor",
        "message": "down due to app replacement",
        "changedate": 1594584860.3647995
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "minor",
        "new_global_status": "minor",
        "message": "down due to colo move",
        "changedate": 1594315937.5278857
    },
    {
        "changetype": "single",
        "service": "retrace",
        "status": "major",
        "new_global_status": "major",
        "message": "down due to colo move",
        "changedate": 1594315881.6486561
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1594315799.467791
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Move to new datacentre",
        "changedate": 1592578657.004953
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "The IAD2 datacentre has a major network issue",
        "changedate": 1592571309.7896087
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "We are running from new datacentre with limited capacity",
        "changedate": 1592066396.5391634
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "scheduled",
        "message": "Everything seems to be working.",
        "changedate": 1591858130.9865751
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Move to new datacentre",
        "changedate": 1591706157.018916
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1590694023.0044227
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "major",
        "new_global_status": "major",
        "message": "bodhi not accepting new updates",
        "changedate": 1590626355.3207653
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "docs",
            "elections"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1590620630.423241
    },
    {
        "changetype": "multiple",
        "services": [
            "docs",
            "elections",
            "bodhi"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Our openshift cluster is having difficulties that we are investigating",
        "changedate": 1590605337.240525
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1590598244.048853
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "major",
        "new_global_status": "major",
        "message": "bodhi is misbehaving, users can experience timeouts",
        "changedate": 1590574029.0192175
    },
    {
        "changetype": "single",
        "service": "cloud",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1589298619.6017425
    },
    {
        "changetype": "single",
        "service": "cloud",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "communishift is moving",
        "changedate": 1586786983.915439
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1586169838.6502697
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "major",
        "new_global_status": "major",
        "message": "Bodhi is having issues",
        "changedate": 1586166334.3473718
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1585271719.3628516
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Everything seems to be working.",
        "changedate": 1585271161.487295
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1584713753.4256656
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "major",
        "new_global_status": "major",
        "message": "Network outage in the RDU2 Data Centre",
        "changedate": 1584710409.7063174
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "fedmsg",
            "koji",
            "packages",
            "pkgs"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1584047726.9305007
    },
    {
        "changetype": "multiple",
        "services": [
            "koji",
            "pkgs",
            "packages",
            "bodhi",
            "fedmsg"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Fedora Messaging is experiencing major problems",
        "changedate": 1584031527.3405125
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "koji"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1583961416.59448
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "major",
        "new_global_status": "major",
        "message": "Build systems are having problems due to rabbitmq problems",
        "changedate": 1583957393.226378
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "Build systems are having problems due to rabbitmq problems",
        "changedate": 1583957359.2614608
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1583877750.4995074
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "Koji is having issues, we are looking into it",
        "changedate": 1583874530.3111525
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1582462503.2810552
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers movement, https://pagure.io/fedora-infrastructure/issue/8668",
        "changedate": 1582437886.6453261
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1582039351.628882
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "testing status",
        "changedate": 1582039283.8099594
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1580981724.0175524
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers are being updated now.",
        "changedate": 1580978864.921905
    },
    {
        "changetype": "single",
        "service": "copr",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Copr servers are being updated now",
        "changedate": 1580978639.1968951
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1579557967.2397752
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "https://pagure.io/fedora-infrastructure/issue/8562",
        "changedate": 1579539846.4242115
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1579251942.7633226
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "koji is not responsive, the problem is under investigation",
        "changedate": 1579248487.647378
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1579128886.8451552
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mbs",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Everything seems to be working.",
        "changedate": 1579122285.709218
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1579045860.4744453
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled buildsystem outage",
        "changedate": 1579035779.1019616
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "Build systems will be offline for reboots",
        "changedate": 1579035714.0713367
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1578335108.5403183
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "minor",
        "new_global_status": "minor",
        "message": "a",
        "changedate": 1578335101.6654305
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1578331593.9381874
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "minor",
        "new_global_status": "minor",
        "message": "Bodhi is under investigation for misbehaving",
        "changedate": 1576161617.961989
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1576061042.9290462
    },
    {
        "changetype": "single",
        "service": "bodhi",
        "status": "major",
        "new_global_status": "major",
        "message": "Something is up with bodhi, we're investigating",
        "changedate": 1576055017.1500926
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1574289572.448806
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Planned koji outage happening now.",
        "changedate": 1574287412.8640726
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1573083679.662184
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Fedora is performing scheduled maintenance across its fleet.",
        "changedate": 1573074136.2027235
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "koji",
            "koschei",
            "pkgs",
            "retrace"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1572992189.4721115
    },
    {
        "changetype": "multiple",
        "services": [
            "koschei",
            "pkgs",
            "koji",
            "bodhi",
            "retrace"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Down for scheduled outage",
        "changedate": 1572987695.9409578
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1570844466.2028818
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "major",
        "new_global_status": "major",
        "message": "We are performing some database maintenance on Koji.",
        "changedate": 1570830195.0971158
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1570810077.3530643
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "minor",
        "new_global_status": "minor",
        "message": "The Koji database is in a degraded speed state. We are investigating",
        "changedate": 1570800315.3683655
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1570054815.4562643
    },
    {
        "changetype": "single",
        "service": "koji",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled koji outage",
        "changedate": 1570050426.6200056
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1566431820.554754
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Planned outage in effect: https://pagure.io/fedora-infrastructure/issue/8107",
        "changedate": 1566420048.3862953
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1566347462.3324146
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "retrace",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Planned staging/build system outage in effect: https://pagure.io/fedora-infrastructure/issue/8106",
        "changedate": 1566332943.3265376
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1562970002.7484283
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7980",
        "changedate": 1562965178.4989932
    },
    {
        "changetype": "single",
        "service": "wiki",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1561683956.0109656
    },
    {
        "changetype": "single",
        "service": "wiki",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7942",
        "changedate": 1561669254.0017903
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1558656923.078359
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "We are in a planned updates outage, see fedora-infrastrcture#7810 for details.",
        "changedate": 1558645108.8900833
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1558486350.7762306
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Update/Reboot of Fedora Services",
        "changedate": 1558473392.0382106
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1556910401.9771357
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7756",
        "changedate": 1556910086.414712
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1556639519.285178
    },
    {
        "changetype": "single",
        "service": "pagure",
        "status": "major",
        "new_global_status": "major",
        "message": "Service is down for needed upgrade",
        "changedate": 1556633272.9454324
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1554946375.4009368
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "All systems are being updated/rebooted",
        "changedate": 1554929920.5532753
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1554895656.8693762
    },
    {
        "changetype": "single",
        "service": "pkgs",
        "status": "major",
        "new_global_status": "major",
        "message": "Service is down for needed upgrade",
        "changedate": 1554894235.1701472
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1554857455.4851525
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7699",
        "changedate": 1554844190.062121
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "wiki",
            "registry",
            "copr",
            "docs",
            "mirrormanager",
            "badges",
            "fas",
            "pagure",
            "website",
            "zodbot",
            "koji",
            "authentication",
            "people",
            "krb",
            "fedocal",
            "blockerbugs",
            "elections",
            "bodhi",
            "pkgs",
            "fedorapaste",
            "fedmsg",
            "koschei",
            "mirrorlist",
            "packages",
            "cloud",
            "mailinglists"
        ],
        "changetype": "multiple",
        "changedate": 1551474967.518052
    },
    {
        "new_global_status": "major",
        "status": "major",
        "message": "We are updating buildsystems",
        "services": [
            "registry",
            "cloud",
            "blockerbugs",
            "koschei",
            "zodbot",
            "docs",
            "krb",
            "badges",
            "bodhi",
            "fedorapaste",
            "fedmsg",
            "wiki",
            "mirrormanager",
            "pkgs",
            "fedocal",
            "fas",
            "people",
            "packages",
            "mailinglists",
            "mirrorlist",
            "pagure",
            "koji",
            "authentication",
            "copr",
            "website",
            "elections"
        ],
        "changedate": 1551472696.4428618,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1551311414.369744,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7591",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1551297533.4838793,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "pkgs",
        "changedate": 1551263933.3649826,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Upgrading to a newer pagure",
        "service": "pkgs",
        "changedate": 1551263811.5679762,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "packages",
        "changedate": 1549963883.746489,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Scheduled maintenance is in progress.",
        "service": "packages",
        "changedate": 1549958369.9282715,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1549155487.9148479,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7535",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1549131017.4177816,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "koji",
        "changedate": 1547417055.3777208,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Scheduled outage of s390x builders is in progress",
        "service": "koji",
        "changedate": 1547243926.0644782,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1545163259.8389895,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7445",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1545156640.8048377,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1541633343.3736548,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "planned outage",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1541624636.502064,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1538618455.4438117,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Planned updates/reboots happening now.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1538600451.9068372,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "koji",
        "changedate": 1538594685.809712,
        "changetype": "single"
    },
    {
        "new_global_status": "major",
        "status": "major",
        "message": "issues with koji hub",
        "service": "koji",
        "changedate": 1538592387.8939424,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "bodhi",
        "changedate": 1538094795.4912026,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "planned outage",
        "service": "bodhi",
        "changedate": 1538090112.4055285,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "registry",
        "changedate": 1534894959.7969387,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Planned rebuild of Fedora Container Registry",
        "service": "registry",
        "changedate": 1534870941.7565722,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1534483469.8105183,
        "changetype": "multiple"
    },
    {
        "new_global_status": "major",
        "status": "major",
        "message": "vpn issues",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1534479447.8497517,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1532066808.3737772,
        "changetype": "multiple"
    },
    {
        "new_global_status": "major",
        "status": "major",
        "message": "Apparent networking outage in our primary colo.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1532066249.8909495,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "service": "people",
        "changedate": 1531253736.6996243,
        "changetype": "single"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Scheduled maintenance in progress",
        "service": "people",
        "changedate": 1531240348.125521,
        "changetype": "single"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1530661963.4621198,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Planned infrastructure-wide outage for updates",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgs",
            "registry",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1530651689.3714063,
        "changetype": "multiple"
    },
    {
        "new_global_status": "good",
        "status": "good",
        "message": "Everything seems to be working.",
        "services": [
            "bodhi",
            "cloud",
            "koji"
        ],
        "changedate": 1530578051.3265083,
        "changetype": "multiple"
    },
    {
        "new_global_status": "scheduled",
        "status": "scheduled",
        "message": "Build and cloud systems down for planned maintenance",
        "services": [
            "bodhi",
            "koji",
            "cloud"
        ],
        "changedate": 1530565631.5523195,
        "changetype": "multiple"
    }
]);