callback([
    {
        "services": [
            "registry",
            "cloud",
            "tagger",
            "blockerbugs",
            "koschei",
            "pkgdb",
            "zodbot",
            "docs",
            "krb",
            "badges",
            "bodhi",
            "fedorapaste",
            "fedmsg",
            "wiki",
            "mirrormanager",
            "pkgs",
            "fedocal",
            "fas",
            "people",
            "packages",
            "mailinglists",
            "mirrorlist",
            "pagure",
            "koji",
            "authentication",
            "copr",
            "website",
            "elections"
        ],
        "changedate": 1551472696.4428618,
        "message": "We are updating buildsystems",
        "changetype": "multiple",
        "status": "major",
        "new_global_status": "major"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1551311414.369744,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1551297533.4838793,
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7591",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "service": "pkgs",
        "changedate": 1551263933.3649826,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "pkgs",
        "changedate": 1551263811.5679762,
        "message": "Upgrading to a newer pagure",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "service": "packages",
        "changedate": 1549963883.746489,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "packages",
        "changedate": 1549958369.9282715,
        "message": "Scheduled maintenance is in progress.",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1549155487.9148479,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1549131017.4177816,
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7535",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "service": "koji",
        "changedate": 1547417055.3777208,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "koji",
        "changedate": 1547243926.0644782,
        "message": "Scheduled outage of s390x builders is in progress",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1545163259.8389895,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1545156640.8048377,
        "message": "scheduled outage: https://pagure.io/fedora-infrastructure/issue/7445",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1541633343.3736548,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1541624636.502064,
        "message": "planned outage",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1538618455.4438117,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1538600451.9068372,
        "message": "Planned updates/reboots happening now.",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "service": "koji",
        "changedate": 1538594685.809712,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "koji",
        "changedate": 1538592387.8939424,
        "message": "issues with koji hub",
        "changetype": "single",
        "status": "major",
        "new_global_status": "major"
    },
    {
        "service": "bodhi",
        "changedate": 1538094795.4912026,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "bodhi",
        "changedate": 1538090112.4055285,
        "message": "planned outage",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "service": "registry",
        "changedate": 1534894959.7969387,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "registry",
        "changedate": 1534870941.7565722,
        "message": "Planned rebuild of Fedora Container Registry",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1534483469.8105183,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1534479447.8497517,
        "message": "vpn issues",
        "changetype": "multiple",
        "status": "major",
        "new_global_status": "major"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1532066808.3737772,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1532066249.8909495,
        "message": "Apparent networking outage in our primary colo.",
        "changetype": "multiple",
        "status": "major",
        "new_global_status": "major"
    },
    {
        "service": "people",
        "changedate": 1531253736.6996243,
        "message": "Everything seems to be working.",
        "changetype": "single",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "service": "people",
        "changedate": 1531240348.125521,
        "message": "Scheduled maintenance in progress",
        "changetype": "single",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1530661963.4621198,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "changedate": 1530651689.3714063,
        "message": "Planned infrastructure-wide outage for updates",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    },
    {
        "services": [
            "bodhi",
            "cloud",
            "koji",
            "pkgdb"
        ],
        "changedate": 1530578051.3265083,
        "message": "Everything seems to be working.",
        "changetype": "multiple",
        "status": "good",
        "new_global_status": "good"
    },
    {
        "services": [
            "bodhi",
            "koji",
            "pkgdb",
            "cloud"
        ],
        "changedate": 1530565631.5523195,
        "message": "Build and cloud systems down for planned maintenance",
        "changetype": "multiple",
        "status": "scheduled",
        "new_global_status": "scheduled"
    }
]);