callback([
    {
        "changetype": "single",
        "service": "registry",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1534894959.7969387
    },
    {
        "changetype": "single",
        "service": "registry",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Planned rebuild of Fedora Container Registry",
        "changedate": 1534870941.7565722
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1534483469.8105183
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "vpn issues",
        "changedate": 1534479447.8497517
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1532066808.3737772
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "major",
        "new_global_status": "major",
        "message": "Apparent networking outage in our primary colo.",
        "changedate": 1532066249.8909495
    },
    {
        "changetype": "single",
        "service": "people",
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1531253736.6996243
    },
    {
        "changetype": "single",
        "service": "people",
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Scheduled maintenance in progress",
        "changedate": 1531240348.125521
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1530661963.4621198
    },
    {
        "changetype": "multiple",
        "services": [
            "authentication",
            "badges",
            "blockerbugs",
            "bodhi",
            "cloud",
            "copr",
            "docs",
            "elections",
            "fas",
            "fedmsg",
            "fedocal",
            "fedorapaste",
            "koji",
            "koschei",
            "krb",
            "mailinglists",
            "mirrorlist",
            "mirrormanager",
            "packages",
            "pagure",
            "people",
            "pkgdb",
            "pkgs",
            "registry",
            "tagger",
            "website",
            "wiki",
            "zodbot"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Planned infrastructure-wide outage for updates",
        "changedate": 1530651689.3714063
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "cloud",
            "koji",
            "pkgdb"
        ],
        "status": "good",
        "new_global_status": "good",
        "message": "Everything seems to be working.",
        "changedate": 1530578051.3265083
    },
    {
        "changetype": "multiple",
        "services": [
            "bodhi",
            "koji",
            "pkgdb",
            "cloud"
        ],
        "status": "scheduled",
        "new_global_status": "scheduled",
        "message": "Build and cloud systems down for planned maintenance",
        "changedate": 1530565631.5523195
    }
]);